#!/bin/sh

# 스테이징 하지 않은 사항은 잠시 보관 ( 청크 단위로 add 했을 때 나중에 파일 단위로 add 되는 것을 막기 위함)
git stash --keep-index --include-untracked

# 1) 스테이지된 Kotlin 파일만
FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.kts?$' || true)
[ -z "$FILES" ] && exit 0

# 2) ktlint 자동 포매팅
echo $FILES
set +e
echo "🔧 ktlint formatting..."
./ktlint -F $FILES
if [ $? -ne 0 ]; then
  echo "✖️ ktlint violations detected. Ktlint Check Failed..."
  set -e
  exit 1
else [ $? -eq 0 ];
  echo "✅ ktlint Check passed"
fi

# 3) 다시 스테이지
git add $FILES

# 5) detekt 자동 수정
echo "🔧 detekt auto-correct..."
./gradlew detektStaged -PstagedFiles="$FILES" --quiet

if [ $? -ne 0 ]; then
  # 검사가 끝났으니 pop으로 보관했던 것 불러옴
  git stash pop --index
  echo "✖️ Detekt violations detected. Detekt Check Failed..."
  set -e
  exit 1
else
  git add $FILES
  git stash pop --index
  echo "✅ Detekt checks passed."
  exit 0
fi

