#!/bin/sh

# 1) 스테이지된 Kotlin 파일만
FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.kts?$' || true)
[ -z "$FILES" ] && exit 0

# 2) ktlint 자동 포매팅
echo $FILES
set +e
echo "🔧 ktlint formatting..."
./ktlint -F $FILES
if [ $? -ne 0 ]; then
  echo "✖️ ktlint violations detected. Ktlint Check Failed..."
  set -e
  exit 1
else [ $? -eq 0 ];
  echo "✅ ktlint Check passed"
fi

# 3) 다시 스테이지
git add $FILES

# 5) detekt 자동 수정
echo "🔧 detekt auto-correct..."
./gradlew detektStaged -PstagedFiles="$FILES" --quiet
if [ $? -ne 0 ]; then
  echo "✖️ Detekt violations detected. Detekt Check Failed..."
  set -e
  exit 1
else
  git add $FILES
  echo "✅ Detekt checks passed."
  exit 0
fi

